Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import time, datetime, psutil
ImportError: No module named psutil
